

<?php
//MESS NOT WITH THIS CODE (UNLESS YOU KNOW WHAT YOU'RE DOING, OF COURSE)
include("./common.php");


//set up SQL connection
	$link = mysql_connect ($server, $user, $password);
		if (! $link)
			{
			die ("Couldn't connect to mySQL server");
			}
		if (!mysql_select_db ($db, $link) )
			{
			die ("Coldn't open $db: ".mysql_error() );
			}
			
			
//spit out listings for multiple properties
	function makelisting($querystring, $link, $guidestring, $cur_page, $listings_per_page, $sort)
		{
		global $use_city_state;
		if ($sort == "") {$sort = "price DESC";}
		$querystring = $querystring." ORDER BY $sort";
		$result = mysql_query("$querystring;",$link);
		$num_rows = mysql_num_rows($result);

		$page_num = $cur_page + 1;
		
		$total_num_page = ceil($num_rows/$listings_per_page);
		
		
		print "<Center>";
		if ($num_rows == "1") {Print "There is currently one listing in this category.<BR>";}
		else {Print "There are currently $num_rows listings in this category.<BR>";}
		
		print "<!-- Results generated by OpenAutoClassifieds. http://jonroig.com/freecode/openautoclassifieds/ --> ";
		
		if ($total_num_page != 0)
			{
			Print "This is page $page_num of $total_num_page. Displaying $listings_per_page listings per page.<BR>";
		
			$prevpage = $cur_page-1;
			$nextpage = $cur_page+1;
			if ($page_num != 1){print "<a href=\"./carview.php?$guidestring&cur_page=$prevpage&sort=$sort\">Previous Page</a>     ";}
			if ($page_num != $total_num_page){print "  <a href=\"./carview.php?$guidestring&cur_page=$nextpage&sort=$sort\">Next Page</a>     ";}
			}
		
		if ($total_num_page > 1)
  				{
  				print "<FORM name=pagejump_top>";
				Print "<SELECT NAME=\"selectpage\" onChange=\"window.location.href=document.pagejump_top.selectpage.options[document.pagejump_top.selectpage.selectedIndex].value\">  ";
					Print "<OPTION VALUE=\"./carview.php?$guidestring&cur_page\" SELECTED>Jump To Another Page ";
					for ($counter=0; $counter<=$total_num_page-1; $counter++)
						{
						$page_jump = $counter +1;
						print "<OPTION VALUE=\"./carview.php?$guidestring&cur_page=$counter&sort=$sort\">Page $page_jump ";
						}
					print "</SELECT>";
				Print "</FORM>";
				}
		
		
		print "<P>";
		
		//handle sort functions
		print "[ Sort by: ";
		
		print "&#160;&#160;<a href=\"./carview.php?$guidestring&sort=price%20DESC\">";
		if ($sort == "price DESC") {print "<B>Price</b>";}
		else {print "Price";}
		
		print "</a>&#160;&#160;<a href=\"./carview.php?$guidestring&sort=id%20DESC\">";
		if ($sort == "id DESC") {print "<B>Most Recent</b>";}
		else {print "Most Recent";}
		
		print "</a>&#160;&#160;<a href=\"./carview.php?$guidestring&sort=miles%20DESC\">";
		if ($sort == "miles DESC") {print "<B>Mileage</b>";}
		else {print "Mileage";}
		
		print "</a>&#160;&#160;<a href=\"./carview.php?$guidestring&sort=year%20DESC\">";
		if ($sort == "year DESC") {print "<B>Year</b>";}
		else {print "Year";}
		
		if ($use_city_state == "Y") {
			print "</a>&#160;&#160;<a href=\"./carview.php?$guidestring&sort=city\">";
			if ($sort == "city") {print "<B>City</b>";}
			else {print "City";}
		}
		
		print "</a> ]<P>";
		//end sort functions
		
		
		$limit_str = "LIMIT ". $cur_page * $listings_per_page .",$listings_per_page";
		$query = "$querystring $limit_str";
		
		
		$result = mysql_query("$query;",$link);
		print "<table width=\"98%\" border=0 cellspacing=0 cellpadding=0>";
			print "<TR>";
				print "<td width=\"16.66%\" align=center>Listing</td>";
				if ($use_city_state == "Y") {print "<td width=\"16.66%\" align=center>City</td>";}
				print "<td width=\"16.66%\" align=center>Make</td>";
				print "<td width=\"16.66%\" align=center>Model</td>";
				print "<td width=\"16.66%\" align=center>Miles</td>";
				print "<td width=\"16.66%\" align=center>Asking Price</td>";
			print "</tr>";

			print "<TR bgcolor=black height=3>";
				print "<td align=center> </td>";
				if ($use_city_state == "Y") {print "<td align=center> </td>";}
				print "<td align=center> </td>";
				print "<td align=center> </td>";
				print "<td align=center> </td>";
				print "<td align=center> </td>";
			print "</tr>";
			
			print "<TR height=5>";
				print "<td align=center> </td>";
				if ($use_city_state == "Y") {print "<td align=center> </td>";}
				print "<td align=center> </td>";
				print "<td align=center> </td>";
				print "<td align=center> </td>";
				print "<td align=center> </td>";
			print "</tr>";
			
			
			print "";

						
			
			while ($a_row =mysql_fetch_array ($result) )
				{
				
				//strip slashes so input appears correctly
				$a_row[$title] = stripslashes($a_row[$title]);
				$a_row[$address] = stripslashes($a_row[$address]);
				$a_row[city] = stripslashes($a_row[city]);
				$a_row[previewdesc] = stripslashes($a_row[previewdesc]);
				$a_row[fulldesc] = stripslashes($a_row[fulldesc]);
				$a_row[type] = stripslashes($a_row[type]);
				$a_row[transmission] = stripslashes($a_row[transmission]);
				$a_row[color] = stripslashes($a_row[color]);
				$a_row[doors] = stripslashes($a_row[doors]);
				$a_row[stereo] = stripslashes($a_row[stereo]);
				$a_row[notes] = stripslashes($a_row[notes]);
				
				//format price & miles
				$a_row[price] = number_format ($a_row[price]);
				$a_row[miles] = number_format ($a_row[miles]);
				
				print "<TR>";
				
				//select images connected to a given listing
				$query = "SELECT * FROM tbl_Files WHERE prop_num = $a_row[id] LIMIT 1";
				$output = mysql_query("$query",$link);
				
				
				
				$count = 0;
				while ($image_row =mysql_fetch_array ($output) )
					{
					
					
					print "<td valign=top align=center width=115><a href=\"./carview.php?view=$a_row[id]\"><img src='image.php?Id=$image_row[id_files]' border=1 width=100 alt=\"Photo\"></a><br></td>";
					$count++;
					}
				
				
				if ($count == 0)
					{
					print "<td valign=top align=center width=115><a href=\"./carview.php?view=$a_row[id]\"><img src=\"./images/nophoto.gif\" border=1 width=100 alt=\"View Listing\"></a><br></td>";
					}	
				
				
				print "</td>";
				if ($use_city_state == "Y") {print "<td align=center>$a_row[city], $a_row[state]</td>";}
				print "<td align=center>$a_row[make]</td>";
				print "<td align=center>$a_row[year] $a_row[model]</td>";
				
				print "<td align=center>$a_row[miles]</td>";
				print "<td align=center>\$$a_row[price]</td>";
				
				print "</tr>";
				
				print "<TR>";
				
				print "<td align=center>Listing: $a_row[id]</td>";
				if ($use_city_state == "Y") {print "<td align=center> </td>";}
				print "<td align=center> </td>";
				print "<td align=center> </td>";
				print "<td align=center> </td>";
				print "<td align=center><a href=\"./carview.php?view=$a_row[id]\">See listing...</a></td>";
				print "</tr>";
				
				print "<TR height=2>";
				if ($use_city_state == "Y") {print "<td align=center> </td>";}
				print "<td align=center> </td>";
				print "<td align=center> </td>";
				print "<td align=center> </td>";
				print "<td align=center> </td>";
				print "<td align=center> </td>";
				print "</tr>";
				
				
				print "<TR bgcolor=black height=1>";
				if ($use_city_state == "Y") {print "<td align=center> </td>";}
				print "<td align=center> </td>";
				print "<td align=center> </td>";
				print "<td align=center> </td>";
				print "<td align=center> </td>";
				print "<td align=center> </td>";
				print "</tr>";
				
				print "<TR height=3>";
				print "<td align=center> </td>";
				print "<td align=center> </td>";
				print "<td align=center> </td>";
				print "<td align=center> </td>";
				print "<td align=center> </td>";
				print "<td align=center> </td>";
				print "</tr>";
				
  				}
  				print "</table>";
  			
			if ($total_num_page > 1)
  				{
  				print "<center><P><FORM name=pagejump>";
				Print "<SELECT NAME=\"selectpage\" onChange=\"window.location.href=document.pagejump.selectpage.options[document.pagejump.selectpage.selectedIndex].value\">  ";
					Print "<OPTION VALUE=\"./carview.php?$guidestring&cur_page\" SELECTED>Jump To Another Page ";
					for ($counter=0; $counter<=$total_num_page-1; $counter++)
						{
						$page_jump = $counter +1;
						print "<OPTION VALUE=\"./carview.php?$guidestring&cur_page=$counter&sort=$sort\">Page $page_jump ";
						}
					print "</SELECT>";
				Print "</FORM>";
				}
				
		if ($total_num_page != 0)
			{
			print "<P>";		
			$prevpage = $cur_page-1;
			$nextpage = $cur_page+1;
			if ($page_num != 1){print "<a href=\"./carview.php?$guidestring&cur_page=$prevpage&sort=$sort\">Previous Page</a>     ";}
			if ($page_num != $total_num_page){print " <a href=\"./carview.php?$guidestring&cur_page=$nextpage&sort=$sort\">Next Page</a>     ";}
			}
				
		Print "</center>";
  		}		

print "<!-- HERE BEGINNETH THE HEADER -->\r\n";
include("./templates/user_top.html");
					
					print "<!-- HERE ENDETH THE HEADER -->\r\n\r\n<!-- THUS BEGINNETH THE MAIN CONTENT -->\r\n";
					

					//BE CAREFUL IN HERE IF YOU DON'T KNOW WHAT YOU'RE DOING
					
					if ($cur_page == "") {$cur_page = 0;}
					
					//SELECT A SPECIFIC PROPERTY
					if ($view != "")
						{

						$query = "SELECT * FROM vehicles WHERE id='$view'";
						$result = mysql_query($query);
						if (!$result) error_message (sql_error());
						
						//strip slashes so input appears correctly
						$a_row = mysql_fetch_array($result);
						
						$a_row[$title] = stripslashes($a_row[$title]);
						$a_row[$address] = stripslashes($a_row[$address]);
						$a_row[city] = stripslashes($a_row[city]);
						$a_row[previewdesc] = stripslashes($a_row[previewdesc]);
						$a_row[fulldesc] = stripslashes($a_row[fulldesc]);
						$a_row[type] = stripslashes($a_row[type]);
						$a_row[transmission] = stripslashes($a_row[transmission]);
						$a_row[color] = stripslashes($a_row[color]);
						$a_row[doors] = stripslashes($a_row[doors]);
						$a_row[stereo] = stripslashes($a_row[stereo]);
						$a_row[notes] = stripslashes($a_row[notes]);
						
						//format price & miles
						$a_row[price] = number_format ($a_row[price]);
						$a_row[miles] = number_format ($a_row[miles]);
				
						// added 28 Nov 2002  MCR
						// Pull up seller's email address.
						// vehicles.agent is text and vehicles.owner is id, both of
						// which can be looked up in agents.  For real estate, agent
						// and owner can be different, but for cars, they should be
						// the same.  Use vehicles.owner as the key for now.
						// Future: Combine this with the query above.
						$query = "SELECT * FROM agents WHERE id='$a_row[owner]'";
						$result = mysql_query($query);
						if (!$result) error_message (sql_error());

						//strip slashes so input appears correctly
						$b_row = mysql_fetch_array($result);
						
						$b_row[$agentemail] = stripslashes($a_row[$agentemail]);
						// added 28 Nov 2002  MCR
						
						
						//print out the listing itself
						Print "<table border=0 cellspacing=0 cellpadding=0 width=\"90%\">";
 						Print "<tr><td><font face=\"arial,ms sans serif\" size=3><b>Listing : $a_row[title] </b></font></td></tr>";
						Print "</table><p>";
						Print "<table border=0 cellspacing=0 cellpadding=2 width=\"550\"><tr><td rowspan=20 valign=top align=center width=165><font size=2 face=\"Arial,Helvetica,Geneva,Swiss,SunSans-Regular\">";
						
						//is there an image?
						//select images connected to a given listing
						$count = 0;
						$query = "SELECT * FROM tbl_Files WHERE prop_num =  $a_row[id]";
						$result = mysql_query("$query",$link);
						while ($image_row =mysql_fetch_array ($result) )
							{
				
							echo "<B>";
							echo stripslashes($image_row[description]) . "<BR>\n";
							echo "</b><table border=1 cellspacing=0 cellpadding=0 width=100><tr><td align=center><a href=\"./image.php?Id=$image_row[id_files]\" target=\"_new\"><img src='image.php?Id=$image_row[id_files]' border=0 width=100 alt='Click to Enlarge'></a></td></tr></table>";
							echo "<P> \n";
							$count++;
	
				
							}
						print "</font>";
						
						if ($count == 0)
     					 	{
     					 	print "<table border=1 cellspacing=0 cellpadding=0 width=100><tr><td align=center><img src=\"./images/nophoto.gif\" border=0 width=100></a></td></tr></table>";
     					 	}  
							
						elseif ($count == 1)
							{
							print "<font face=\"arial\" size=1><b>Click photo to enlarge</b></font><br><br><p>";
							}
						else
							
							{
							print "<font face=\"arial\" size=1><b>Click photos to enlarge</b></font><br><br><p>";
							}

						
						Print "</td><td valign=top>";
   						
						print "<table><tr><TD width=300>";
						print "Make: $a_row[make]<BR>";
						Print "Model: $a_row[model]<BR>";
						print "Year: $a_row[year]<BR>";
						Print "Condition: $a_row[body]";
						print "</td><td width=300>";
						Print "Price: \$$a_row[price]<BR>";
						Print "Mileage: $a_row[miles]<BR>";
						Print "Color: $a_row[color]<BR>";
						Print "Type: $a_row[type]</td></tr>";
						
						print "<tr height=8><td colspan=2> </td></tr>";
						
						print "<tr><td width=300 align=left>";
						print "Doors: $a_row[doors]<BR>";
						print "Transmission: $a_row[transmission]<BR>";
						print "Drivetrain: $a_row[drivetrain]<BR>";
						print "Stereo: $a_row[stereo]<P>";
						
						
						print "</td><td width=300 valign=top align=left>";
						//is the $use_city_state option selected?
						if ($use_city_state == "Y") {
   							Print "<font face=\"ms sans serif\" size=2><BR>City: $a_row[city]<BR>State: $a_row[state]<br>
   							Zip: $a_row[zip]<BR>";
   							}
   						print "</td></tr>";
   						print "<TR><TD align=left>Features:</td><td>";
   						
   						//deal with features
   						$featuresarray = explode("||", $vehiclefeatureoptions);
  						while (list($IndexValue, $FeatureItem) = each ($featuresarray))
  							{
  							$realindex = $IndexValue+1; 
							$optnum = "opt".$realindex;   							
  							if ($a_row[$optnum] == 'Y') {print "$FeatureItem<BR>";}
  							
  							}
  			print "</td></tr>";
  			
   						
   						
   						print "<tr height=8><td colspan=2> </td></tr>";
   						print "<P><tr><td align=left colspan=2>$a_row[fulldesc]</td></tr>";
   						
   						print "<tr height=15><td colspan=2> </td></tr>";

							
						if ($friendmail == "Y")
							{
							Print "<tr><td width=300 align=left><font face=\"ms sans serif\" size=2>Send to a Friend:&nbsp;</font></td>";
							Print "<td width=300><font face=\"ms sans serif\" size=2><a href=\"./friendmail.php?listing=$a_row[id]\">Click Here to email this listing</a></font></td></tr>";
							
							}
							
						// added 28 Nov 2002  MCR
// uncommented 12-10-02 dsr, prevents table from closing.
						Print "</td></tr></table>";
						Print "</td></tr><tr>";
   					Print "<td align=left>Seller contact:</td>";
   					Print "<td align=left>$b_row[agentemail]</td>";
						Print "</td></tr></table>";
						// added 28 Nov 2002  MCR
						
						}
						
					
						
					else
						//if it's not a single listing, just what is it you'd like to see?
						{
						
					
						//set up minimum and maximum price
						if ($minprice == "")
							{
							$minprice = 0;
							}
						if ($maxprice == "")
							{
							$maxprice = 1000000000000000;
							}
						//get rid of extra junk in min and max price
						$minprice = ereg_replace("%24","",$minprice);
						$maxprice = ereg_replace("%24","",$maxprice);
						$minprice = ereg_replace("%2C","",$minprice);
						$maxprice = ereg_replace("%2C","",$maxprice);
						$minprice = ereg_replace("[^[:alnum:]]","",$minprice);
						$maxprice = ereg_replace("[^[:alnum:]]","",$maxprice);
						
						//start building querystring and guidestring
						//the querystring is the mySQL query itself, while
						//guidestring is the actual url of the search -- it's used
						//to pass along data so you can jump to different pages easily
						
						$querystring = "SELECT * FROM vehicles WHERE ";
						$querystring = $querystring."(price >= '$minprice' AND price <= '$maxprice')";
						
						$guidestring = "minprice=$minprice&maxprice=$maxprice";
						
						
						foreach ($HTTP_GET_VARS as $key=>$value)
							{
							
							
								
								
							if ($key == "citystate")
								{
								$count = 0;
								$extra = "";
								$querystring = $querystring." AND (";	
								foreach ($value as $two_dim_value)
									{
									//deal with city and state selection
									
									//break apart city and state
									$guidestring = $guidestring."&citystate%5B%5D=$two_dim_value";
									$buffer = explode("___" , $two_dim_value);
									$city = $buffer[0];
									$state = $buffer[1];
									if ($count > 0) {$extra = " OR ";}
									$querystring = $querystring."$extra(city='$city' and state='$state')";
									$count++;
									}
								$querystring = $querystring.")";
								}
							
							elseif ($key == "makemodelchoice")
								{
								$count = 0;
								$extra = "";
								$querystring = $querystring." AND (";	
								foreach ($value as $two_dim_value)
									{
									//deal with make and model selection
									
									//break apart make and model
									$guidestring = $guidestring."&makemodelchoice%5B%5D=$two_dim_value";
									$buffer = explode("___" , $two_dim_value);
									$make = $buffer[0];
									$model = $buffer[1];
									if ($count > 0) {$extra = " OR ";}
									$querystring = $querystring."$extra(make='$make' and model='$model')";
									$count++;
									}
								$querystring = $querystring.")";
								}
							
							elseif ($key == "yearchoice")
								{
								$count = 0;
								$extra = "";
								$querystring = $querystring." AND (";	
								foreach ($value as $year)
									{
									//deal with year selection
									
									//break apart make and model
									$guidestring = $guidestring."&yearchoice%5B%5D=$year";
									if ($count > 0) {$extra = " OR ";}
									$querystring = $querystring."$extra(year='$year')";
									$count++;
									}
								$querystring = $querystring.")";
								}

							elseif ($key == "minprice")
								{
								//do not do anything further -- already handled
								}
							elseif ($key == "maxprice")
								{
								//do not do anything further -- already handled
								}
							elseif ($key == "typechoice")
								{
								$count = 0;
								$extra = "";
								$querystring = $querystring." AND (";
								foreach ($value as $two_dim_value)
									{
									$guidestring = $guidestring."&typechoice%5B%5D=$two_dim_value";
									if ($count > 0) {$extra = " OR ";}
									$querystring = $querystring."$extra(type='$two_dim_value')";
									$count++;
									}
								$querystring = $querystring.")";
								}
							elseif ($key == "makechoice")
								{
								$count = 0;
								$extra = "";
								$querystring = $querystring." AND (";
								foreach ($value as $two_dim_value)
									{
									$guidestring = $guidestring."&makechoice%5B%5D=$two_dim_value";
									if ($count > 0) {$extra = " OR ";}
									$querystring = $querystring."$extra(make='$two_dim_value')";
									$count++;
									}
								$querystring = $querystring.")";
								}
							elseif ($key == "transmissionchoice")
								{
								$count = 0;
								$extra = "";
								$querystring = $querystring." AND (";
								foreach ($value as $two_dim_value)
									{
									$guidestring = $guidestring."&transmissionchoice%5B%5D=$two_dim_value";
									if ($count > 0) {$extra = " OR ";}
									$querystring = $querystring."$extra(transmission='$two_dim_value')";
									$count++;
									}
								$querystring = $querystring.")";
								}

							elseif ($key == "cur_page")
								{
								//do nothing -- dealt with elsewhere
								}
							elseif ($key == "sort")
								{
								//handle the way the page sorts data
								//do nothing now -- dealt with elsewhere
								}
							
							else
								{
								$guidestring = $guidestring."&$key=$value";
								$querystring = $querystring." AND $key = '$value'";

								}
							}
							
						
						
						//remove the comment marks below if you want help diagnosing problems
						//or want to view the actual strings being passed to mySQL
						//print "$querystring<BR>";
						//print "$guidestring<BR>";
						
						makelisting($querystring, $link, $guidestring, $cur_page, $listings_per_page, $sort);
						}
					
		//print the footer
		print"\r\n<!-- THUS ENDETH THE MAIN CONTENT -->\r\n<!-- HERE BEGINNETH THE FOOTER -->";
		include("./templates/user_bottom.html");
		
		//gots to close the mysql connection
		mysql_close($link);

?>
